init(
draw, setDisplaySize: x=320 y=240
logic, setCursor: x=0 y=0;
textdraw, drawText(i), font=0
var, i = "Uh-oh! The system can't find the BIOS and the system has failed to start. If you have misplaced your boot files, this might be the reason. If you haven't touched your files, please re-flash them either through the virtual wrapper, or holding the pressing the Reset button 3 times and the system should re-flash the BIOS. This may have been done by a malicious program program, so setting the WriteAbleBIOS flag is not reccomended. If you have a read-only BIOS, this may mean hardware failure.";;
);
