init(
draw, setDisplaySize: x=320 y=240
logic, setCursor: x=0 y=0;
textdraw, drawText(i), font=0
var, i = "Uh-oh! It seems the XF-ZOS has crashed. If you are seeing this screen, you may have installed incorrect hardware into your system that isn't compatible with other hardware, or you may have software incompatibility. If you have recently installed new software, try uninstalling it. You may also want to reset the BIOS, as this may have caused problems as well. This won't cause you to lose data, unless you have data stored in XBA, or a custom firmware. If you have tried all of these, try re-formatting your system, if that doesn't help, it may be a hardware problem."
);
